export const RESULT_CREATE_REQUEST = 'RESULT_CREATE_REQUEST'
export const RESULT_CREATE_SUCCESS = 'RESULT_CREATE_SUCCESS'
export const RESULT_CREATE_FAIL = 'RESULT_CREATE_FAIL'

export const RESULT_CREATE_RESET = 'RESULT_CREATE_RESET'

export const RESULT_LIST_MY_REQUEST = 'RESULT_LIST_MY_REQUEST'
export const RESULT_LIST_MY_SUCCESS = 'RESULT_LIST_MY_SUCCESS'
export const RESULT_LIST_MY_FAIL = 'RESULT_LIST_MY_FAIL'
export const RESULT_LIST_MY_RESET = 'RESULT_LIST_MY_RESET'